### ISSUE TITLE
Global Operators (Conjunction, Disjunction and Negation) Syntax Error

### ISSUE THREAD

**Issue by LEARNTAU** [IDNI/tau-lang#3]
I tried to run the demo demo_1.1-basic_syntax_and_history.tau and got errors on global operators
I got the recent Tau version 0.7 (v0.7-alpha)
I'm running it on Windows with Virtual Machine Ubuntu OS. 
The Tau demo run perfectly from the beginning but suddenly got error in this part.

![Global Operators Syntax Error](https://github.com/user-attachments/assets/33ab76c7-c2f4-40b4-a929-5259261a6014)

**Comment by mp-004** [comment]
Similar Syntax error here.  I can confirm.
![2024-11-16 20-53-04](https://github.com/user-attachments/assets/b0ff7901-241d-4e4c-8b9a-9b27412cc205)

**Comment by castrod** [comment]
Demo scripts have been revised to update the syntax. All demo scripts have now the correct one.

**Comment by LEARNTAU** [comment]
Thanks David for a very fast response! 

What I noticed in the update is that
1. &&& change to &  
2. ||| change to |
3. - was removed in the new update

Could you kindly give some thoughts as to what happened to global operators? 
1. Does this mean global operators are now same as Boolean operators? 
2. What about the global operator negation "-" 

Thank you very much!
