### ISSUE TITLE
Formulas that involve constants over the Tau Boolean algebra Syntax Error [seg fault]

### ISSUE THREAD

**Issue by LEARNTAU** [IDNI/tau-lang#4]
I tried to run the demo demo_1.1-basic_syntax_and_history.tau and got errors.
I got the recent Tau version 0.7 (v0.7-alpha)
I'm running it on Windows with Virtual Machine Ubuntu OS.
I need to close the terminal as the program hangs. 
![image](https://github.com/user-attachments/assets/54afa65b-a056-4c43-ac5e-61ce7e8eb990)

**Comment by castrod** [comment]
The error happens when parsing constants using old style syntax:

({ : i1[t]'o1[t] = 0. } i1[t] = 0) ? (o1[t] = 0) : (o1[t] = 1)

**Comment by LEARNTAU** [comment]
Now that The syntax is fixed, I tried to run the formula by adding input and output but I got an error message
Error (empty program) when I provided input value of either 0 or 1 at time t = 0. 

![image](https://github.com/user-attachments/assets/31ce2ce8-a929-4566-a0dc-08c13bac6e18)

**Comment by LEARNTAU** [comment]
![photo_2024-11-20_08-12-25](https://github.com/user-attachments/assets/d4699762-8da8-49fb-9fd5-e0419cbe30b7)

**Comment by LEARNTAU** [comment]
Hi tklip, yes I run the same and now it's working well.
![v0 7-alpha-86-ga66ca93](https://github.com/user-attachments/assets/353a8591-7d5c-4159-8a28-a62cc09d254e)

Ohad said it was a major bug and now it's fix. thanks!

**Comment by LEARNTAU** [comment]
> This should be resolved. I've just tried these examples in latest build and I don't see any issue.

Hi tklip, I think this was a major bug and was fixed.
