### ISSUE TITLE
Compilation error (and possible solution)

### ISSUE THREAD

**Issue by mp-004** [IDNI/tau-lang#5]
OS: Fedora Linux 41 (Workstation Edition) x86_64
Kernel: Linux 6.11.7-300.fc41.x86_64
Tau Language Framework Alpha version 0.7 (2024-11-16 build 3912dcb)

> I'm leaving this here in case anyone else encounters this problem. There must be some sort of incompatibility with the versions of CMake and Boost I have installed, but I have managed to compile successfully.

I tried running `release.sh` but it failed. I think I've fixed it by installing `boost-devel` as well as adding the following lines below the "Adding Boost log library" comment (`CMakeLists.txt` file):

`cmake_policy(SET CMP0167 OLD)`
`set(Boost_USE_STATIC_LIBS OFF)`
`find_package(Boost REQUIRED COMPONENTS log)`

**Comment by tklip** [comment]
boost::log is statically linked so on Fedora also `boost-static` is required and it should build just fine (even with the policy not set)
