### ISSUE TITLE
Inconsistent normalization of T and F constants with xor operator

### ISSUE THREAD

**Issue by pt7k** [IDNI/tau-lang#6]
Tau version: 0.7 (v0.7-alpha-8-g6541a42)
OS: x86_64 Ubuntu Linux 5.15.0-125

While normalizing a pair of Tau formula constants with ^ (xor) operator, the two combinations T^T and F^F are being normalized using the Boolean function normalizer resulting in 0 instead of F, but the other two combinations T^F and F^T are normalized as Tau formula resulting in T.

![image](https://github.com/user-attachments/assets/0bde467d-399f-48b5-87f7-df28d35636fc)

**Comment by LEARNTAU** [comment]
Tau version: 0.7 (v0.7-alpha-9-g687b64d)
OS: Ubuntu 22.04.5 LTS (64-bit)

Yes, I got the same result when running Tau at build-Release
![image](https://github.com/user-attachments/assets/2146fca6-0420-4916-ad00-549f9dd83035)

**Comment by castrod** [comment]
Fix it in commit https://github.com/IDNI/tau-lang/commit/fb8b3a5ff02c762842888f660fa75fcb6c4d6933.

**Comment by castrod** [comment]
The issue was related to hooks in wff's (simplification rules on node creation). I've added several test to check it.

**Comment by pt7k** [comment]
> The issue was related to hooks in wff's (simplification rules on node creation). I've added several test to check it.

Great! That's a comprehensive update.

**Comment by pt7k** [comment]
Thanks for replying to my post at tau.forum today.
